version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresDB:/data/postgres
    # volumes:
    #   - /home/user/pgdata:/var/lib/postgresql/data # Bind mount to host directory

    env_file:
      - ../.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ../.env
    ports:
      - "5050:80"
volumes:
  postgresDB:   # this creates a volume on the host in /var/lib/docker/volumes (it is protected so you might need sudo)

  # docker volume ls
  #
  # docker volume rm 

# mkdir -p /home/user/pgdata
# sudo chown 999:999 /home/user/pgdata
# sudo chmod 700 /home/user/pgdata

# psql 
# docker exec -it postgres_db psql -U myuser -d mydatabase